### PR TITLE
fix unicode encoding

### PR DESCRIPTION
**Pull request by Geminist**

### CODE REVIEW

**Comment by alexsaveliev** [comment]
Thanks for the patch!

**Comment by Geminist** [comment]
@alexsaveliev, when the release with this patch is expected?

**Comment by alexsaveliev** [comment]
@Geminist hopefully soon, I have to ping another person who is in charge of releases, because I don't have enough privileges, sorry

**Comment by alexsaveliev** [comment]
@Geminist 

https://mvnrepository.com/artifact/com.codeminders.socketio/socket-io/1.0.10

**Pull request merged**
